# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Fast CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    name: fast test on OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v3

      - name: setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          # only first java setup need enable cache
          cache: maven
      - name: build and test with Java 17 without agents
        run: ./mvnw -V --no-transfer-progress clean install
      - name: test under hello and world agents
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: hello-and-world-agents
      - name: test under hello agent
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent
          STUDY_AGENT_ENABLE_CLASS_LOG: true
      - name: test under hello agent twice
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent-twice
      - name: run Main without agents
        run: ./mvnw dependency:properties exec:exec -pl main-runner
      - name: run Main under hello and world agents
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: hello-and-world-agents
      - name: run Main under hello agent
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent
          STUDY_AGENT_ENABLE_CLASS_LOG: true
      - name: run Main under hello agent twice
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent-twice

      - name: setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - name: test with Java 8 without agents
        run: ./mvnw -V --no-transfer-progress dependency:properties surefire:test
      - name: test under hello and world agents
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: hello-and-world-agents
      - name: test under hello agent
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent
          STUDY_AGENT_ENABLE_CLASS_LOG: true
      - name: test under hello agent twice
        run: ./mvnw dependency:properties surefire:test
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent-twice
      - name: run Main without agents
        run: ./mvnw dependency:properties exec:exec -pl main-runner
      - name: run Main under hello and world agents
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: hello-and-world-agents
      - name: run Main under hello agent
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent
          STUDY_AGENT_ENABLE_CLASS_LOG: true
      - name: run Main under hello agent twice
        run: ./mvnw dependency:properties exec:exec -pl main-runner
        env:
          STUDY_AGENT_RUN_MODE: only-hello-agent-twice

      - name: 'remove self maven install files(OS: *nix)'
        run: rm -rf $HOME/.m2/repository/io/foldright/study*
        # https://docs.github.com/en/actions/learn-github-actions/expressions
        # https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        if: runner.os != 'Windows'
      - name: 'remove self maven install files(OS: Windows)'
        run: Remove-Item -Recurse -Force $home/.m2/repository/io/foldright/study*
        if: runner.os == 'Windows'
